SELECT * FROM JPN_AUTHOR;
SELECT * FROM JPN_AUTHOR_SEMINAR;
SELECT * FROM JPN_BOOK;
SELECT * FROM JPN_BOOK_AUTHOR;
SELECT * FROM JPN_CARD;
SELECT * FROM JPN_COPIES;
SELECT * FROM JPN_CUSTOMER;
SELECT * FROM JPN_EVENT;
SELECT * FROM JPN_CUSTOMER_EXHIBITION;
SELECT * FROM JPN_EXHIBITION;
SELECT * FROM JPN_INVOICE;
SELECT * FROM JPN_PAYMENT;
SELECT * FROM JPN_PAYPAL;
SELECT * FROM JPN_RENTAL;
SELECT * FROM JPN_RESERVATION;
SELECT * FROM JPN_ROOM;
SELECT * FROM JPN_SEMINAR;
SELECT * FROM JPN_SPONSOR;
SELECT * FROM JPN_SPONSOR_SEMINAR;
SELECT * FROM JPN_TOPIC;

SELECT COUNT(*) AS AUTHOR_COUNT FROM JPN_AUTHOR;

SELECT COUNT(*) AS AUTHOR_SEMINAR_COUNT FROM JPN_AUTHOR_SEMINAR;

SELECT COUNT(*) AS BOOK_COUNT FROM JPN_BOOK;

SELECT COUNT(*) AS BOOK_AUTHOR_COUNT FROM JPN_BOOK_AUTHOR;

SELECT COUNT(*) AS CARD_COUNT FROM JPN_CARD;

SELECT COUNT(*) AS COPIES_COUNT FROM JPN_COPIES;

SELECT COUNT(*) AS CUSTOMER_COUNT FROM JPN_CUSTOMER;

SELECT COUNT(*) AS EVENT_COUNT FROM JPN_EVENT;

SELECT COUNT(*) AS CUSTOMER_EXHIBITION_COUNT FROM JPN_CUSTOMER_EXHIBITION;

SELECT COUNT(*) AS EXHIBITION_COUNT FROM JPN_EXHIBITION;

SELECT COUNT(*) AS INVOICE_COUNT FROM JPN_INVOICE;

SELECT COUNT(*) AS PAYMENT_COUNT FROM JPN_PAYMENT;

SELECT COUNT(*) AS PAYPAL_COUNT FROM JPN_PAYPAL;

SELECT COUNT(*) AS RENTAL_COUNT FROM JPN_RENTAL;

SELECT COUNT(*) AS RESERVATION_COUNT FROM JPN_RESERVATION;

SELECT COUNT(*) AS ROOM_COUNT FROM JPN_ROOM;

SELECT COUNT(*) AS SEMINAR_COUNT FROM JPN_SEMINAR;

SELECT COUNT(*) AS SPONSOR_COUNT FROM JPN_SPONSOR;

SELECT COUNT(*) AS SPONSOR_SEMINAR_COUNT FROM JPN_SPONSOR_SEMINAR;

SELECT COUNT(*) AS TOPIC_COUNT FROM JPN_TOPIC;