ALTER TABLE JPN_CUSTOMER
ADD CUST_PASSWORD VARCHAR(255) NOT NULL;

ALTER TABLE JPN_CUSTOMER
ADD CONSTRAINT unique_email UNIQUE (CUST_EMAIL);

CREATE INDEX idx_email ON JPN_CUSTOMER (CUST_EMAIL);

CREATE TABLE JPN_USER (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_FNAME VARCHAR(50) NOT NULL,
    USER_LNAME VARCHAR(50) NOT NULL,
    USER_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    USER_PHONE VARCHAR(30),
    USER_UID_TYPE VARCHAR(20),
    USER_UID_NO VARCHAR(50),
    USER_PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL CHECK (ROLE IN ('customer', 'employee')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

